### ISSUE TITLE
Possibly a bad path on Linux

### ISSUE THREAD

**Issue by phaedryx** [Terria-K/FortRise#4]
My son has been trying to run FortRise, but there seems to be an issue on Linux. This is the error that I am seeing when I select the "Launch TowerFall" button:

```
   at FortLauncher.Launcher.MenuButtons_LaunchTowerFall() in D:\Project\FNA Project\FortLauncher\Launcher\Widgets\MenuButtons.cs:line 127
System.ComponentModel.Win32Exception (8): An error occurred trying to start process '/home/mungus/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/TowerFall/TowerFall.exe' with working directory '/home/mungus/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/TowerFall'. Exec format error
```

My guess is that it is assuming an `.exe` file, but being Linux, that won't work. Other than the `TowerFall.exe` the path would be correct.

**Comment by Terria-K** [comment]
Use the new launcher called [pyrgos](https://github.com/Terria-K/pyrgos). I am no longer maintaining the old launcher anymore.
